### ISSUE TITLE
axoltol is trying to load data set from hugging face rather than disk

### ISSUE THREAD

**Issue by MrMuhannadObeidat** [tuanh123789/Spark-TTS-finetune#6]
axoltol is trying to load data set from hugging face rather than disk

my config entries:

datasets:
  - path: json
    data_files: ["aisha-1.0.jsonl"]
    type: completion

dataset_prepared_path: "aisha_sparktts/"

Error message:

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/datasets/json/resolve/main/aisha-1.0.jsonl

```

**Comment by MrMuhannadObeidat** [comment]
Fixed by changing the configs to this (based on axotol docs):

```
datasets:
  - path: aisha_sparktts/aisha-1.0.jsonl
    type: completion

 dataset_prepared_path:
```
